stephlaf/cavebnb

db/migrate/20180813205846_add_name_to_caves.rb, db/schema.rb
=> Added name col to Cave

app/controllers/caves_controller.rb
=> Controller!

config/initializers/inflections.rb, config/routes.rb
=> Code routes

app/controllers/bookings_controller.rb, app/controllers/caves_controller.rb
Behold, the bookings controller!
=> Bookings controller

app/assets/stylesheets/components/avatar.css, app/assets/stylesheets/components/banner.css, app/assets/stylesheets/components/button.css, app/assets/stylesheets/components/card.css, db/schema.rb
behold my beautiful whatnot . . . before we even have views!
=> first round of css components -- card, button, banner, avatar

db/migrate/20180814153216_add_column_to_caves.rb, db/schema.rb
=> Added description column to caves table

db/migrate/20180814182103_remove_amenities_from_caves.rb, db/schema.rb
=> Removed amenities col from caves

db/seeds.rb
=> Added cleaning method to the db:seed, and photos

app/views/layouts/application.html.erb
=> Moved alerts above navbar

app/models/amenity.rb, app/models/cave.rb, app/models/cave_amenity.rb, db/cave_schema.xml, db/migrate/20180814190750_create_amenities.rb, db/migrate/20180814191337_create_cave_amenities.rb, db/schema.rb, test/models/amenity_test.rb, test/models/cave_amenity_test.rb
=> Added Amenity model and CaveAmenity joining table

app/views/bookings/new.html.erb
created a new partial file for booking only to realize I didn't need it
=> didn't do anything

app/models/review.rb, app/views/caves/new.html.erb, db/migrate/20180814203249_create_reviews.rb, db/schema.rb, test/models/review_test.rb
added a numericality validation to review.rb
=> changed rating to accept only numbers

app/models/cave.rb
=> Added a search method in Cave model to filter by amenity id.

db/cave_schema.xml
just added a photo table to the schema and photo column to users in the xml file.
=> added photo table in schema

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/layouts/_index.scss, app/assets/stylesheets/layouts/_sign-in.scss, app/views/devise/registrations/new.html.erb
=> Sign in styling

config/initializers/devise.rb
=> Unless signed-in, redirected to sing-in/login page

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
the devise code is now visible, we can create a user and edit it in users/edit
=> the edit profile page is now visible in /users/edit

db/schema.rb
The schema in master was the WRONG ONE!!!
=> this is the real schema

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/layouts/_sign-in.scss, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, config/initializers/simple_form_extension.rb, config/locales/simple_form_extension.en.yml, config/locales/simple_form_extension.fr.yml
cleaned up the submit a photo button
=> added cool photo submit for signup

app/assets/stylesheets/layouts/_user.scss, app/views/users/show.html.erb
Added a route to the edit page from users
=> added route to edit in user page

Gemfile, Gemfile.lock, app/controllers/caves_controller.rb, app/javascript/packs/map.js, app/models/cave.rb, app/views/bookings/show.html.erb, app/views/caves/_map.html.erb, app/views/caves/show.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, config/webpack/map.js, db/migrate/20180817152509_add_coordinates_to_caves.rb, db/schema.rb, db/seeds.rb, package.json, yarn.lock
=> Making map on show
